##
## EPITECH PROJECT, 2024
## Makefile
## File description:
## -> Makefile
##

all:
	cp main.py zappy_AI
	chmod 555 zappy_AI
	mv zappy_AI ../

clean:
	rm -rf __pycache__

fclean: clean

re: fclean all