##
## EPITECH PROJECT, 2024
## Makefile
## File description:
## -> Makefile
##

all:
	cp main.py zappy_AI
	chmod 777 zappy_AI
	mv zappy_AI ../

clean:
	rm -rf __pycache__

fclean: clean
		rm ../zappy_AI

re: fclean all
