name: Mirror Repository

on:
  push:
    branches:
      - main  # Change this to the branch you want to mirror
  schedule:
    - cron: '0 * * * *'  # Run every hour (adjust as necessary)

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source Repository
      uses: actions/checkout@v2

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        cat ~/.ssh/id_rsa

    - name: Set up Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Push to mirror
      run: |
        git push --mirror mirror
